apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gh9ew3/springboot:v2
        ports:
        - containerPort: 9000
          protocol: TCP
          name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  selector:
    app: app
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9000
